=== mbensiali/mbe/java/gpa/xml_schema/repertoire.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
		targetNamespace="http://courtalon.com/repertoire"
		xmlns:tns="http://courtalon.com/repertoire" elementFormDefault="qualified">

	<element name="repertoire">
		<complexType>
			<sequence>
				<element name="entree" maxOccurs="unbounded">
					<complexType>
						<sequence>
							<element name="nom" type="string" />
							<element name="prenom" type="string" />
							<element name="adresse" maxOccurs="unbounded">
								<complexType>
									<sequence>
										<element name="no" type="string" />
										<element name="rue" type="string" />
										<element name="codepostal" type="string" />
										<element name="ville" type="string" />
										<element name="pays" type="string" />
									</sequence>
								</complexType>
							</element>
						</sequence>
						<attribute name="no" type="integer" use="required" />
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>
</schema>

=== mbensiali/mbe/java/gpa/xml_schema/repertoire.xml
<?xml version="1.0" encoding="UTF-8"?>
<repertoire xmlns="http://courtalon.com/repertoire"
			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:schemaLocation="http://courtalon.com/repertoire repertoire.xsd" >
  <entree no="1">
    <nom>Courtalon</nom>
    <prenom>Vincent</prenom>
    <adresse>
    	<no>23</no>
    	<rue>rue maillot</rue>
    	<codepostal>75016</codepostal>
    	<ville>paris</ville>
    	<pays>FR</pays>
    </adresse>
  </entree>
  <entree no="2">
    <nom>Bob</nom>
    <prenom>Joe</prenom>
    <adresse>
    	<no>23</no>
    	<rue>rue maillot</rue>
    	<codepostal>75016</codepostal>
    	<ville>paris</ville>
    	<pays>FR</pays>
    </adresse>
  </entree>
  <entree no="3">
    <nom>Bohn</nom>
    <prenom>bobby</prenom>
    <adresse>
    	<no>23</no>
    	<rue>rue maillot</rue>
    	<codepostal>75016</codepostal>
    	<ville>paris</ville>
    	<pays>FR</pays>
    </adresse>
  </entree>
   
</repertoire>
